local _, MD = ...

--------------------------------------------------------------------------------
-- Shipped healer intuition (docs/SPEC-v0.13.md §11). GENERATED by
-- tools/buildintuition.lua from imported Warcraft Logs fights -- do not hand
-- edit; rebuild it.
--
-- Rates are FRACTIONS OF MAX HEALTH PER SECOND, blurred to the nearest 0.5%,
-- because a number read off this file is not a fact about anybody's next pull.
-- `open` is the first 10 seconds, `rest` the remainder, `spread` the ratio
-- between the busiest and quietest fight in the corpus for that role -- a role
-- that swings by five times between encounters is not worth believing much.
--
-- Built 2026-09-09 from 22 fight(s) across 13 encounter(s).
--   Kael'thas Sunstrider                           1
--   Reliquary of Souls                             1
--   The Lurker Below                               1
--   Nightbane                                      10
--   Attumen the Huntsman                           1
--   Mother Shahraz                                 1
--   Kaz'rogal                                      1
--   Shade of Akama                                 1
--   Void Reaver                                    1
--   Shade of Aran                                  1
--   Leotheras the Blind                            1
--   Gruul the Dragonkiller                         1
--   Magtheridon                                    1
--------------------------------------------------------------------------------

MD.IntuitionTBC = {
    version = 1, built = "2026-09-09", fights = 22, encounters = 13,
    blurred = 0.0050,
    source = "Warcraft Logs, TBC Anniversary (fresh)",
    all = {
        TANK = { open = 0.0900, rest = 0.0550, n = 20, spread = 5.1 },
        HEALER = { open = 0.0000, rest = 0.0150, n = 20, spread = 23.5 },
        DAMAGER = { open = 0.0000, rest = 0.0150, n = 22, spread = 5.0 },
    },
    zones = {
        ["Nightbane"] = {
            TANK = { open = 0.1100, rest = 0.0450, n = 10 },
            HEALER = { open = 0.0000, rest = 0.0200, n = 10 },
            DAMAGER = { open = 0.0000, rest = 0.0100, n = 10 },
        },
    },
}
